version: '3.9'

services:

  redis:
    image: redis:latest
    restart: always

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - redis
      - mysql
    environment:
      REDIS_HOST: redis
      REDIS_PASSWORD: null
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: password
    volumes:
      - ./app/src:/var/www/html
      - ./composer.json:/var/www/html/composer.json

    command: php-fpm

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./app/src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
